# GitHub Pages Configuration for DashOPS Documentation

title: DashOPS Documentation
description: Cloud Operations Platform - Beta Documentation
url: https://dash-ops.github.io
baseurl: ""

# Theme
theme: minima
kramdown:
  syntax_highlighter: rouge

# Navigation
header_pages:
  - README.md
  - getting-started.md
  - api-reference.md
  - plugins/README.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - node_modules/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/

# SEO
author: DashOPS Team
twitter:
  username: dashops
facebook:
  username: dashops

# Google Analytics (when ready)
# google_analytics: UA-XXXXXXXXX-X
