name: DashOpsCI

on:
  push:
    paths-ignore:
      - 'docs/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Tests Go environment
      uses: actions/setup-go@v3
      with:
        go-version: '^1.23.4'
    - run: |
        go test -v ./...
